
//# publish
module 0xCAFE::Calc {
    public fun add_and_return_sum(a: u8, b: u8): u8 {
        let sum = a + b;
        sum
    }

    public fun lambda_adder(x: u8, y: u8): u8 {
        let add_lambda: |u8, u8|u8 has copy+drop = |a: u8, b: u8| {
            a + b
        };
        add_lambda(x, y)
    }

    public inline fun inline_add(a: u8, b: u8): u8 {
        a + b
    }

    public fun call_inline_twice(a: u8, b: u8): u8 {
        let first = inline_add(a, b);
        let second = inline_add(b, first);
        second
    }
}


//# run 0xCAFE::Calc::add_and_return_sum --args 10u8 20u8


//# run 0xCAFE::Calc::lambda_adder --args 15u8 25u8


//# run 0xCAFE::Calc::call_inline_twice --args 5u8 7u8


//# publish
module 0xCAFE::Caller {
    use 0xCAFE::Calc;

    public fun call_add_and_return(a: u8, b: u8): u8 {
        let res = Calc::add_and_return_sum(a, b);
        res
    }

    public fun call_lambda_adder(a: u8, b: u8): u8 {
        let res = Calc::lambda_adder(a, b);
        res
    }

    public fun call_call_inline_twice(a: u8, b: u8): u8 {
        let res = Calc::call_inline_twice(a, b);
        res
    }
}


//# run 0xCAFE::Caller::call_add_and_return --args 3u8 6u8


//# run 0xCAFE::Caller::call_lambda_adder --args 4u8 12u8


//# run 0xCAFE::Caller::call_call_inline_twice --args 1u8 2u8


// Featurres:
// e0d671ef5e56e3c17cc028f58558e133: Test that the Move function correctly computes the addition of two u8 values before returning a specific value.
// 02a0d162ad59e2910b98dd07a8d9cb41: Write functions containing lambda (anonymous function) expressions.
// 9f38a2013886067cef890651dcf5f9f0: Test that calling an inline function from one module within another module correctly performs the nested function calls and returns the expected result.
// 7acd1e41f4fece9e8328f064d6b1de5a: Separate different sections with blank lines for clarity.
// 4f9dca3978e52525e078943c566ac00d: Attach generated bytecode to the model after successful compilation.
// 5c5cd022a0ae658e161cf5429140e791: Handle function parameters and return types by creating and tracking temporary variables.
