
//# publish
module 0xCAFE::HexByteStrings {
    // This module tests hex byte string literals and tuple destructuring with let bindings

    public fun get_hex_bytes(): vector<u8> {
        let hex: vector<u8> = x"CAFEBABE";
        hex
    }

    public fun destructure_tuple(): (u64, bool, vector<u8>) {
        let tup = (42u64, true, x"DEADBE");
        let (num, flag, bytes) = tup;
        (num, flag, bytes)
    }

    public fun runner() {
        let hex_bytes = get_hex_bytes();
        let (a, b, c) = destructure_tuple();

        // Using the bound variables to avoid "unused variable" warnings
        let _t = hex_bytes.len() + (a as u64);
        let _x = if b { 1u64 } else { 0u64 };
        let _y = c.len();
    }
}


//# run 0xCAFE::HexByteStrings::runner


// Featurres:
// 9a42e06a9229d7c6adf6b846b10e1593: Create hex byte strings with 'x""' prefix.
// 4f9dca3978e52525e078943c566ac00d: Attach generated bytecode to the model after successful compilation.
// 6ddbaac7fd4a97dd727f7448a5805473: Use let bindings that destructure or bind multiple values ('lvalues') with corresponding expressions on the right-hand side in a single statement
