//# publish
address 0x1 {
    module UnitTypes {
        /// This module tests unit types definition and usage,
        /// reference safety, and inline function with closures.

        /// Define unit types using zero-sized structs
        struct Meter has copy, drop, store {}
        struct Second has copy, drop, store {}

        /// Function demonstrating reference safety annotations
        public fun safe_references(m: &Meter, s: &mut Second) {
            // Reference safety with immutable and mutable references
            // This should pass safety checks, no invalid aliasing.
            let _m_borrowed: &Meter = m;
            let _s_borrowed: &mut Second = s;
        }

        /// A function with specific code blocks that have conditions and expressions
        public fun condition_blocks(x: u64): u64 {
            if (x > 10) {
                let y = x * 2;
                y
            } else if (x == 10) {
                let y = x + 5;
                y
            } else {
                let y = 0;
                y
            }
        }

        /// Inline function that accepts a closure with no parameters and returns u64
        public inline fun inline_closure_no_args<F: copy + drop + store>(f: F): u64
            where F: Fn() -> u64
        {
            f()
        }

        /// Inline function that accepts a closure with one u64 parameter and returns u64
        public inline fun inline_closure_one_arg<F: copy + drop + store>(f: F, val: u64): u64
            where F: Fn(u64) -> u64
        {
            f(val)
        }

        /// Runner function to test closures and other features
        public fun run() {
            // Use condition_blocks function
            let c1 = condition_blocks(20);
            let c2 = condition_blocks(10);
            let c3 = condition_blocks(5);

            // Test inline closure no args
            let res1 = inline_closure_no_args(|| 42u64);

            // Test inline closure with one arg
            let res2 = inline_closure_one_arg(|x| x * 3, 7u64);

            // Use safe_references
            let m = Meter {};
            let mut s = Second {};
            safe_references(&m, &mut s);

            // Dummy usage to avoid warnings
            let _ = (c1, c2, c3, res1, res2);
        }
    }
}
//# run 0x1::UnitTypes::run

//# publish
address 0x1 {
    module BytecodeModel {
        use std::vector;
        use std::string;

        /// This module models attaching generated bytecode to a model
        struct Bytecode has key {
            bytes: vector<u8>,
        }

        /// Store the bytecode in a resource under the signer's account
        public fun attach_bytecode(account: &signer, bytecode: vector<u8>) {
            move_to(account, Bytecode { bytes: bytecode });
        }

        /// Dummy function to test attaching bytecode (simulate input)
        public fun run(attacher: &signer) {
            // Just attach a vector of bytes representing bytecode
            let dummy_bytecode = vector::empty<u8>();
            vector::push_back(&mut dummy_bytecode, 0xAA);
            vector::push_back(&mut dummy_bytecode, 0xBB);
            attach_bytecode(attacher, dummy_bytecode);
        }
    }
}
//# run 0x1::BytecodeModel::run --signers 0x1

//# publish
address 0x1 {
    module SourceParser {
        use std::string;
        use std::vector;

        /// Represents a documentation comment associated with a code element
        struct DocComment has copy, drop, store {
            text: string::String,
        }

        /// Represents a position in the source code
        struct Position has copy, drop, store {
            line: u64,
            column: u64,
        }

        /// Represents a parsed Move source file element with doc comments
        struct SourceElement has copy, drop, store {
            doc: DocComment,
            code: string::String,
            pos: Position,
        }

        /// Parse a string representing Move source code and extract elements with docs
        public fun parse_move_source(src: &string::String): vector<SourceElement> {
            // For simplicity, we will parse lines and associate lines starting with /// as docs
            let lines = string::split(src, '\n');
            let mut result = vector::empty<SourceElement>();
            let mut i = 0;
            while (i < vector::length(&lines)) {
                let line = *vector::borrow(&lines, i);

                if (string::starts_with(line, "///")) {
                    // Collect consecutive doc lines
                    let mut doc_lines = vector::empty<string::String>();
                    while (i < vector::length(&lines) && string::starts_with(*vector::borrow(&lines, i), "///")) {
                        let doc_line = string::sub_string(*vector::borrow(&lines, i), 3, string::length(*vector::borrow(&lines, i)));
                        vector::push_back(&mut doc_lines, doc_line);
                        i = i + 1;
                    }
                    // Collect next line as code
                    if (i < vector::length(&lines)) {
                        let code_line = *vector::borrow(&lines, i);
                        let combined_doc = string::concat_vec(&doc_lines);
                        let element = SourceElement {
                            doc: DocComment { text: combined_doc },
                            code: code_line,
                            pos: Position { line: i + 1, column: 0 },
                        };
                        vector::push_back(&mut result, element);
                        i = i + 1;
                    }
                } else {
                    i = i + 1;
                }
            }
            result
        }

        /// Runner to parse a small sample source string
        public fun run() {
            let sample_source = string::utf8(b"/// This is a test module\nmodule Test {\n  /// A function\n  fun foo() {}\n}\n");
            let elements = parse_move_source(&sample_source);

            // Dummy usage to avoid warnings
            let len = vector::length(&elements);
            let _ = len;
        }
    }
}
//# run 0x1::SourceParser::run

//# run
script {
    use 0x1::UnitTypes;

    fun main() {
        // Call run function of UnitTypes to test all features in module
        UnitTypes::run();
    }
}