// Test file: conditional_sequence_join.transactional.move

// 1. Conditional Statement Test in Script

//# run
script {
    use std::debug;
    fun main(choice: bool) {
        if (choice) {
            debug::print(&b"Branch True");
        } else {
            debug::print(&b"Branch False");
        }
    }
}

/* Explanation:
 This script tests a simple conditional statement.
 It can succeed along either path depending on the bool argument.
 Bytecode will be generated by compiling the script.
*/

// 2. Module for Sequence Join and File Format Generation

//# publish
module 0x1::StringJoiner {
    use std::string;
    use std::vector;

    // Joins displayable strings with a delimiter
    public fun join_with_delimiter(items: &vector<string::String>, delimiter: &string::String): string::String {
        let len = vector::length(items);
        if (len == 0) {
            string::utf8(b"")
        } else {
            let out = string::clone(vector::borrow(items, 0));
            let i = 1;
            while (i < len) {
                string::push(&mut out, delimiter);
                string::push(&mut out, vector::borrow(items, i));
                i = i + 1;
            };
            out
        }
    }

    /// "Runner" that creates a vector of strings, joins with a delimiter, prints the result
    public fun test_sequence_joiner() {
        use std::debug;
        let items = vector::empty<string::String>();
        vector::push_back(&mut items, string::utf8(b"apple"));
        vector::push_back(&mut items, string::utf8(b"banana"));
        vector::push_back(&mut items, string::utf8(b"carrot"));
        let delimiter = string::utf8(b", ");
        let output = Self::join_with_delimiter(&items, &delimiter);
        debug::print(&output);
    }
}

//# run 0x1::StringJoiner::test_sequence_joiner --signers 0x1

// 3. Another script to join things and print, for file format testing

//# run
script {
    use std::string;
    use std::vector;
    use std::debug;

    fun main() {
        let items = vector::empty<string::String>();
        vector::push_back(&mut items, string::utf8(b"foo"));
        vector::push_back(&mut items, string::utf8(b"bar"));
        vector::push_back(&mut items, string::utf8(b"baz"));
        // Reuse local join logic (copy-paste for the script)
        let len = vector::length(&items);
        let delimiter = string::utf8(b" | ");
        let out = if (len == 0) {
            string::utf8(b"")
        } else {
            let acc = string::clone(vector::borrow(&items, 0));
            let i = 1;
            while (i < len) {
                string::push(&mut acc, &delimiter);
                string::push(&mut acc, vector::borrow(&items, i));
                i = i + 1;
            };
            acc
        };
        debug::print(&out);
    }
}