[generation]
######## Module Related ########
num_modules = { min = 1, target = 1, max = 1 }
num_scripts = { min = 0, target = 0, max = 0 }
num_functions_in_module = { min = 3, target = 5, max = 32 }
num_structs_in_module = { min = 1, target = 3, max = 32 }
num_enum_in_module = { min = 1, target = 3, max = 32 }

######## Struct Related ########
num_fields_in_struct = { min = 0, target = 4, max = 32 }
total_num_composite_type_in_struct = { min = 1, target = 5, max = 32 }
num_type_params_in_struct = { min = 0, target = 2, max = 32 }

######## Enum Related ########
num_variants_in_enum = { min = 1, target = 3, max = 32 }
num_fields_in_enum_variant = { min = 0, target = 2, max = 32 }
total_num_composite_type_in_enum = { min = 1, target = 5, max = 32 }
num_type_params_in_enum = { min = 0, target = 2, max = 32 }

######## Function Related ########
num_params_in_func = { min = 0, target = 4, max = 10 }
num_type_params_in_func = { min = 0, target = 2, max = 32 }
num_inline_funcs = { min = 0, target = 0, max = 2 }
num_nested_calls = { min = 0, target = 3, max = 8 }
num_nested_func_type = { min = 0, target = 3, max = 8 }

######## Block Related ########
num_stmts_in_sequence = { min = 0, target = 3, max = 4 }
num_sequences_in_block = { min = 0, target = 5, max = 8 }

######## Expression Related ########
expr_depth = { min = 1, target = 4, max = 8 }
hex_byte_str_size = { min = 1, target = 32, max = 512 }

######## Type Related ########
type_depth = { min = 1, target = 4, max = 50 }
num_elem_in_tuple = { min = 1, target = 4, max = 50 }

######## Execution ########
num_runs_per_func = { min = 1, target = 3, max = 10 }
generation_timeout_sec = 5

[priorities]
######## Expression ########
ExpressionGenerator = 1
ExprOfTypeGenerator = 1
EOTFuncCallGenerator = 5
EOTVariableGenerator = 10
EOTMatchGenerator = 3
EOTIfElseGenerator = 3
EOTDereferenceGenerator = 8
# Expressions that only work for one type
EOTFuncValGenerator = 5
EOTNumberOpsGenerator = 5
EOTNumberGenerator = 5
EOTReferenceGenerator = 10
EOTStructGenerator = 5
EOTTupleGenerator = 5
EOTBoolGenerator = 5
EOTUnitGenerator = 5
EOTEnumGenerator = 5

######## Statement ########
StatementGenerator = 1
StmtAssignDerefGenerator = 3
StmtExprGenerator = 5
LetAssignGenerator = 5
LetCallGenerator = 3
LetDeclGenerator = 2

######## Basic Nodes ########
# They are directly used by other generators
TupleGenerator = 1
PatternGenerator = 1
TypedNumberGenerator = 1
MatchArmGenerator = 1
AssignDerefGenerator = 1
AssignPatternGenerator = 1
CallableGenerator = 1
CallArgumentsGenerator = 1
EnumMatchGenerator = 1

######## Top Level ########
ProgramGenerator = 1
ModuleGenerator = 1
ScriptGenerator = 1
StructGenerator = 1
EnumGenerator = 1
FunctionGenerator = 1
BlockGenerator = 1
SequenceGenerator = 1
SignatureGenerator = 1
ProducerGenerator = 1
ProducersGenerator = 1
RunnerGenerator = 1
RunnersGenerator = 1
