use crate::{
    constraints::Constraint,
    label::{GenLabel, LabelledGenerator},
    states::StatePool,
    ASTNode, Register,
};
use anyhow::Result;
use arbitrary::Unstructured;
use log::{error, info};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Debug, Clone)]
pub struct GeneratorEntry {
    pub label: GenLabel,
    pub parents: Vec<GenLabel>,
    /// If true, the generator doesn't implement subtree and compose and forward the constraint to its children.
    /// If true, some child node must present
    /// Forwarding nodes can still implement check_constraint and check_ast
    pub forward: bool,

    /// If true, the generator's parents will be set as forwarding nodes
    pub skip_parent: bool,
}

impl GeneratorEntry {
    pub fn new<T: LabelledGenerator>() -> Self {
        GeneratorEntry {
            label: T::label(),
            parents: vec![],
            forward: false,
            skip_parent: false,
        }
    }

    pub fn with_parent<T: LabelledGenerator>(mut self) -> Self {
        self.parents.push(T::label());
        self
    }

    pub fn with_forward(mut self, forward: bool) -> Self {
        self.forward = forward;
        self
    }

    pub fn with_skip_parent(mut self, skip_parent: bool) -> Self {
        self.skip_parent = skip_parent;
        self
    }

    pub fn add_parent<T: LabelledGenerator>(&mut self) {
        self.parents.push(T::label());
    }
}

pub trait Generator<A: ASTNode, C: Constraint>: Register<GeneratorEntry> {
    /// 1. Check whether a constraint is well-formed for this generator.
    /// 2. [Optional] Check whether the constraint is possible to satisfy in the current environment.
    // fn check_constraint(&self, env: Ref<StatePool<A>>, constraint: &C) -> bool;
    fn check_constraint(&self, env: &StatePool<A>, constraint: &C) -> bool;

    /// 1. From the constraint, decide the subtrees to generate.
    /// 2. For each subtree, generate its required constraints.
    /// 3. Register the subtrees using labels.
    fn subtrees(
        &self,
        u: &mut Unstructured,
        env: &mut StatePool<A>,
        constraint: &C,
    ) -> Result<(Vec<Subtree<A, C>>, C)>;

    /// 1. ASTs are generated by the registered subtrees from register_subtrees().
    /// 2. Compose the ASTs into a single ASTNode.
    /// 3. Update any necessary environment information.
    fn compose(
        &self,
        u: &mut Unstructured,
        env: &mut StatePool<A>,
        constraint: C,
        asts: Vec<A>,
    ) -> Result<A>;

    /// Check whether the ASTNode follows the given constraint.
    fn check_ast(
        &self,
        env: &StatePool<A>,
        gen_constraint: &C,
        comp_constraint: &C,
        ast: &A,
    ) -> bool;
}
pub type GeneratorT<A, C> = Box<dyn Generator<A, C>>;

pub enum Subtree<A: ASTNode, C: Constraint> {
    Candidates(CandidateSubtree<A>),
    Generator(GeneratorSubtree<C>),
}

impl<A, C> Subtree<A, C>
where
    A: ASTNode,
    C: Constraint,
{
    pub fn new_single_candidate(candidate: A) -> Self {
        Subtree::Candidates(CandidateSubtree {
            candidates: vec![candidate],
        })
    }

    pub fn new_candidates_subtree(candidates: Vec<A>) -> Self {
        Subtree::Candidates(CandidateSubtree { candidates })
    }

    pub fn new_generator_subtree(generator_label: GenLabel, constraints: C) -> Self {
        Subtree::Generator(GeneratorSubtree {
            generator_label,
            constraints,
        })
    }
}

pub struct CandidateSubtree<A: ASTNode> {
    pub candidates: Vec<A>,
}

pub struct GeneratorSubtree<C: Constraint> {
    pub generator_label: GenLabel,
    pub constraints: C,
}

pub struct GeneratorPool<ASTNode, Constraint> {
    pub initialized: bool,
    pub generators: BTreeMap<GenLabel, GeneratorT<ASTNode, Constraint>>,
    // Contains the parent -> children relationship
    pub dependencies: BTreeMap<GenLabel, Vec<GenLabel>>,
    pub entries: BTreeMap<GenLabel, GeneratorEntry>,
    pub to_skip: BTreeSet<GenLabel>,
}

impl<ASTNode, Constraint> GeneratorPool<ASTNode, Constraint> {
    pub fn empty() -> Self {
        GeneratorPool {
            initialized: false,
            generators: BTreeMap::new(),
            dependencies: BTreeMap::new(),
            entries: BTreeMap::new(),
            to_skip: BTreeSet::new(),
        }
    }

    pub fn register_generator(&mut self, generator: GeneratorT<ASTNode, Constraint>) {
        let entry = generator.register();
        info!("Registering generator: {}", entry.label);
        self.generators.insert(entry.label.clone(), generator);
        self.entries.insert(entry.label.clone(), entry.clone());

        // Keep a record of the parent -> children relationship
        // However, now a parent might not exist in the registry yet
        for parent in entry.parents {
            self.dependencies
                .entry(parent.clone())
                .or_default()
                .push(entry.label.clone());
            self.to_skip.insert(parent.clone());
        }
    }

    pub fn initialize(&mut self) -> bool {
        if self.initialized {
            return true;
        }

        for label in &self.to_skip {
            if let Some(entry) = self.entries.get_mut(label) {
                entry.forward = true;
            }
        }

        let mut visited = vec![];
        let mut to_visit = vec![];
        for label in self.dependencies.keys() {
            if !self.generators.contains_key(label) {
                error!(
                    "Parent generator {} not found for children: {:?}",
                    label,
                    self.dependencies.get(label).unwrap()
                );
                return false;
            }
            to_visit.push(label);
        }

        // Make sure there is no cyclic dependency
        while let Some(label) = to_visit.pop() {
            visited.push(label);
            if let Some(children) = self.dependencies.get(label) {
                for child in children {
                    if visited.contains(&child) {
                        error!("Cyclic dependency detected: {label:?} --> {child:?}");
                        return false;
                    }
                    to_visit.push(child);
                }
            }
        }

        // Make sure forwarding nodes have children
        for label in self.dependencies.keys() {
            if let Some(entry) = self.get_entry(label) {
                if entry.forward {
                    if let Some(children) = self.dependencies.get(label) {
                        if children.is_empty() {
                            error!("Forwarding node {label} has no children");
                            return false;
                        }
                    }
                }
            }
        }

        self.initialized = true;
        true
    }

    pub fn get_entry(&self, label: &GenLabel) -> Option<&GeneratorEntry> {
        self.entries.get(label)
    }

    pub fn get_entry_mut(&mut self, label: &GenLabel) -> Option<&mut GeneratorEntry> {
        self.entries.get_mut(label)
    }

    /// Return the labels for all registered generators.
    pub fn all(&self) -> Vec<GenLabel> {
        self.generators.keys().cloned().collect()
    }

    /// Return a reference to the generator with the given label.
    pub fn get(&self, label: &GenLabel) -> Option<&GeneratorT<ASTNode, Constraint>> {
        self.generators.get(label)
    }

    /// Returns all generators that specialize the given labelled generator.
    /// Set `skip_forward` to true to exclude all forwarding nodes.
    pub fn generators_from(&self, label: &GenLabel, skip_forward: bool) -> Vec<GenLabel> {
        let mut visited = vec![];
        let mut stack = vec![label.clone()];
        while let Some(label) = stack.pop() {
            if visited.contains(&label) {
                panic!("Cyclic dependency detected: {visited:?} --> {label:?}");
            }
            if let Some(entry) = self.get_entry(&label) {
                if skip_forward {
                    if !entry.forward {
                        visited.push(label.clone());
                    }
                } else {
                    visited.push(label.clone());
                }
            }
            if let Some(dependencies) = self.dependencies.get(&label) {
                stack.extend(dependencies.iter().cloned());
            }
        }
        visited
    }
}
