[fuzz]
jobs = 32
cost_usd_limit = 5.0
generations = 100
features = [
    "data/feature_rust_with_embeddings.json",
    "data/feature_transactional_with_embeddings.json",
    "data/feature_markdown.json",
    "data/feature_pr.json",
]
save_all_tests = false
save_all_compilable = true
fix_attempt_limit = 2
enable_static_fixer = true
enable_static_fixer_llm = false
enable_dynamic_fixer_hint = true
enable_feature_rewriter = false

[prompt]
generation_system = ["prompts/common_error_fix_short.md"]
generation_prefix = [
    "prompts/transactional_format.md",
    "prompts/move_example.md",
]
move_examples = ["prompts/move_examples"]
dynamic_error_fixes = ["prompts/dynamic_error_fixes"]
static_error_fixes = ["prompts/static_error_fixes"]
mutations = ["prompts/mutations"]

[fuzz.feature_combination]
init = 20           # Initial population size
mu = 200            # Population size
lam = 30            # Offspring size
tests_per_combo = 1

[fuzz.mutation]
combo_size_max = 10
mutation_rate = 0.7
cross_over_rate = 0.3

semantic_mutation_rate = 0.5
merge_mutation_rate = 0.5
list_mutation_rate = 0.5

[initial]
soft_number_of_goals = 5
soft_number_of_concepts_per_pr = 5
number_of_features_per_concept = 3
soft_final_number_of_combos = 20
generation_attempt_limit = 3
fix_attempt_limit = 3
features = ["data/feature_pr.json"]


[models.default]
# name = "gpt-4.1-nano"
# name = "gpt-4.1-mini"
# name = "gpt-4.1"
name = "claude-3-5-haiku-20241022"
temperature = 0.8

[models.extract]
# name = "gpt-4.1"
# name = "claude-sonnet-4-20250514"
name = "claude-3-5-haiku-20241022"
temperature = 0.5

[models.init]
name = "gpt-4.1-mini"
# name = "claude-sonnet-4-20250514"
# name = "claude-3-5-haiku-20241022"
temperature = 0.5
