use crate::{
    ast::ASTNode,
    env::Environment,
    label::{GenLabel, Labelled},
    types::Type,
};
use arbitrary::Unstructured;
use linkme::distributed_slice;
use log::info;
use std::{
    cell::{Ref, RefMut},
    collections::BTreeMap,
};

// New Label for Self, Generator, The Label that this generator specializes
#[distributed_slice]
pub static GENERATORS: [fn() -> (GenLabel, GeneratorT, Option<GenLabel>)];

pub trait Generator {
    /// 1. Check whether a constraint is well-formed for this generator.
    /// 2. [Optional] Check whether the constraint is possible to satisfy in the current environment.
    fn check_constraint(&self, env: Ref<Environment>, constraint: &Constraint) -> bool;

    /// 1. From the constraint, decide the subtrees to generate.
    /// 2. For each subtree, generate its required constraints.
    /// 3. Register the subtrees using labels.
    fn subtrees(
        &self,
        u: &mut Unstructured,
        env: RefMut<Environment>,
        constraint: &Constraint,
    ) -> Vec<Subtree>;

    /// 1. ASTs are generated by the registered subtrees from register_subtrees().
    /// 2. Compose the ASTs into a single ASTNode.
    /// 3. Update any necessary environment information.
    fn compose(
        &self,
        u: &mut Unstructured,
        env: RefMut<Environment>,
        asts: Vec<ASTNode>,
    ) -> ASTNode;

    /// 1. Used only when the generator is replaced by another generator implementing it.
    /// 2. Check whether the ASTNode is well-formed for this generator.
    fn check_ast(&self, env: Ref<Environment>, constraint: &Constraint, ast: ASTNode) -> bool;
}
pub type GeneratorT = Box<dyn Generator>;

/// This should be extended to a very generic constraint system.
/// Ideally, we should leverage the type system to check whether a constraint is well-formed.
/// For now, we will use a simple key-value store and let the Generators to implement the check.
#[derive(Debug, Clone, Default)]
pub struct Constraint {
    pub types: BTreeMap<String, Type>,
    pub numbers: BTreeMap<String, usize>,
    pub boolean: BTreeMap<String, bool>,
    pub strings: BTreeMap<String, String>,
}

pub enum Subtree {
    Candidates(CandidateSubtree),
    Generator(GeneratorSubtree),
}

impl Subtree {
    pub fn new_single_candidate(candidates: ASTNode) -> Self {
        Subtree::Candidates(CandidateSubtree {
            candidates: vec![candidates],
        })
    }

    pub fn new_candidates_subtree(candidates: Vec<ASTNode>) -> Self {
        Subtree::Candidates(CandidateSubtree { candidates })
    }

    pub fn new_generator_subtree(generator_label: GenLabel, constraints: Constraint) -> Self {
        Subtree::Generator(GeneratorSubtree {
            generator_label,
            constraints,
        })
    }
}

pub struct CandidateSubtree {
    pub candidates: Vec<ASTNode>,
}

pub struct GeneratorSubtree {
    pub generator_label: GenLabel,
    pub constraints: Constraint,
}

pub struct GeneratorPool {
    pub generators: BTreeMap<GenLabel, GeneratorT>,
    pub dependencies: BTreeMap<GenLabel, Vec<GenLabel>>,
}

impl GeneratorPool {
    pub fn new() -> Self {
        let mut generators = BTreeMap::new();
        let mut dependencies = BTreeMap::new();

        GENERATORS.iter().for_each(|generator| {
            let (label, generator, parent) = generator();
            info!("Registering generator: {}", label);
            generators.insert(label.clone(), generator);

            // Keep a record of the parent -> children relationship
            // However, now a parent might not exist in the registry yet
            if let Some(parent) = parent {
                dependencies
                    .entry(parent)
                    .or_insert_with(Vec::new)
                    .push(label);
            }
        });

        for label in dependencies.keys() {
            if !generators.contains_key(label) {
                panic!(
                    "Parent generator {} not found for children: {:?}",
                    label,
                    dependencies.get(label).unwrap()
                );
            }
        }

        // TODO: need to check for cycles in the dependencies

        GeneratorPool {
            generators,
            dependencies,
        }
    }

    pub fn generators(&self) -> Vec<GenLabel> {
        self.generators.keys().cloned().collect()
    }

    /// Returns all generators that specialize the given labelled generator.
    /// This includes the input generator itself.
    pub fn generators_from(&self, label: &GenLabel) -> Vec<GenLabel> {
        let mut visited = vec![];
        let mut stack = vec![label.clone()];
        while let Some(label) = stack.pop() {
            if visited.contains(&label) {
                panic!("Cyclic dependency detected: {:?} --> {:?}", visited, label);
            }
            visited.push(label.clone());
            if let Some(dependencies) = self.dependencies.get(&label) {
                stack.extend(dependencies.iter().cloned());
            }
        }
        visited
    }

    pub fn get(&self, label: &GenLabel) -> Option<&GeneratorT> {
        self.generators.get(label)
    }
}
