[package]
name = "move-smith-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
afl = "*"
honggfuzz = "0.5"
libfuzzer-sys = "0.4.7"
msmith = { path = "../msmith" }
once_cell = "1.19.0"
rand = "0.8.5"

[[bin]]
name = "v1v2"
path = "fuzz_targets/v1v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "afl-v1v2"
path = "fuzz_targets/afl_v1v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "random"
path = "fuzz_targets/random.rs"
test = false
doc = false
bench = false

[[bin]]
name = "opt-noopt"
path = "fuzz_targets/opt_noopt.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hfuzz-v1v2"
path = "fuzz_targets/hfuzz_v1v2.rs"
test = false
doc = false
bench = false

[[bin]]
name = "v2-only"
path = "fuzz_targets/v2_only.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hfuzz-v2-opt-levels"
path = "fuzz_targets/hfuzz_v2_opt_levels.rs"
test = false
doc = false
bench = false

[[bin]]
name = "hfuzz-default"
path = "fuzz_targets/hfuzz_default.rs"
test = false
doc = false
bench = false

[[bin]]
name = "default"
path = "fuzz_targets/default.rs"
test = false
doc = false
bench = false
