[package]
name = "move-test-runner"
edition = "2021"

[dependencies]
utils = { path = "../utils" }
move-model = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-model", branch = "main" }
move-transactional-test-runner = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-transactional-test-runner", branch = "main" }
move-vm-runtime = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-vm-runtime", branch = "main" }
log = "0.4.22"

[[bin]]
name = "move-test-runner"
path = "src/main.rs"
