[package]
name = "msmith"
edition = "2021"

[features]
default = ["git_deps"]
git_deps = [
    "move-compiler-v2",
    "move-model",
    "move-package",
    "move-transactional-test-runner",
]
local_deps = [
    "move-compiler-v2-local",
    "move-model-local",
    "move-package-local",
    "move-transactional-test-runner-local",
]

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true }
clap = { workspace = true }
enuminto = { workspace = true }
env_logger = { workspace = true }
framework = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
move-compiler-v2 = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-compiler-v2", optional = true }
move-compiler-v2-local = { path = "../../aptos-core/third_party/move/move-compiler-v2", package = "move-compiler-v2", optional = true }
move-model = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-model", optional = true }
move-model-local = { path = "../../aptos-core/third_party/move/move-model", package = "move-model", optional = true }
move-package = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-package", optional = true }
move-package-local = { path = "../../aptos-core/third_party/move/tools/move-package", package = "move-package", optional = true }
move-transactional-test-runner = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-transactional-test-runner", optional = true }
move-transactional-test-runner-local = { path = "../../aptos-core/third_party/move/testing-infra/transactional-test-runner", package = "move-transactional-test-runner", optional = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[[bin]]
name = "msmith-debug"
path = "src/main.rs"

[[bin]]
name = "msmith"
path = "src/cli/main.rs"

[[bin]]
name = "msmith-local"
path = "src/cli/main.rs"
required-features = ["local_deps"]

[lib]
name = "msmith"
path = "src/lib.rs"
