[package]
name = "msmith"
edition = "2021"

[features]
default = ["git_deps"]
git_deps = [
    "move-compiler-v2",
    "move-model",
    "move-package",
    "move-transactional-test-runner",
    # "aptos-transactional-test-harness",
]
local_deps = [
    "move-compiler-v2-local",
    "move-model-local",
    "move-package-local",
    "move-transactional-test-runner-local",
    # "aptos-transactional-test-harness-local",
]
legacy_deps = [
    "move-compiler-v2-legacy",
    "move-model-legacy",
    "move-package-legacy",
    "move-transactional-test-runner-legacy",
    # "aptos-transactional-test-harness-legacy",
]

[dependencies]
anyhow = { workspace = true }
arbitrary = { workspace = true }
clap = { workspace = true }
enuminto = { workspace = true }
env_logger = { workspace = true }
framework = { workspace = true }
indicatif = { workspace = true }
log = { workspace = true }
num-bigint = { workspace = true }
move-compiler-v2 = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-compiler-v2", optional = true, branch = "main" }
move-compiler-v2-local = { path = "../../aptos-core/third_party/move/move-compiler-v2", package = "move-compiler-v2", optional = true }
move-compiler-v2-legacy = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-compiler-v2", optional = true, rev = "2389654a796b329b74323acafcd1fc600c170cfa" }
move-model = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-model", optional = true, branch = "main" }
move-model-local = { path = "../../aptos-core/third_party/move/move-model", package = "move-model", optional = true }
move-model-legacy = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-model", optional = true, rev = "2389654a796b329b74323acafcd1fc600c170cfa" }
move-package = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-package", optional = true, branch = "main" }
move-package-local = { path = "../../aptos-core/third_party/move/tools/move-package", package = "move-package", optional = true }
move-package-legacy = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-package", optional = true, rev = "2389654a796b329b74323acafcd1fc600c170cfa" }
move-transactional-test-runner = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-transactional-test-runner", optional = true, branch = "main" }
move-transactional-test-runner-local = { path = "../../aptos-core/third_party/move/testing-infra/transactional-test-runner", package = "move-transactional-test-runner", optional = true }
move-transactional-test-runner-legacy = { git = "https://github.com/aptos-labs/aptos-core.git", package = "move-transactional-test-runner", optional = true, rev = "2389654a796b329b74323acafcd1fc600c170cfa" }
# aptos-transactional-test-harness = { git = "https://github.com/aptos-labs/aptos-core.git", package = "aptos-transactional-test-harness", optional = true, branch = "main" }
# aptos-transactional-test-harness-local = { path = "../../aptos-core/aptos-move/aptos-transactional-test-harness", package = "aptos-transactional-test-harness", optional = true }
# aptos-transactional-test-harness-legacy = { git = "https://github.com/aptos-labs/aptos-core.git", package = "aptos-transactional-test-harness", optional = true, rev = "2389654a796b329b74323acafcd1fc600c170cfa" }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
id-arena = { workspace = true }

[[bin]]
name = "msmith-debug"
path = "src/debug.rs"

[[bin]]
name = "msmith"
path = "src/cli/main.rs"

[[bin]]
name = "msmith-local"
path = "src/cli/main.rs"
required-features = ["local_deps"]

[[bin]]
name = "msmith-legacy"
path = "src/cli/main.rs"
required-features = ["legacy_deps"]

[lib]
name = "msmith"
path = "src/lib.rs"
